// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
//
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });
//
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });
//
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
//
// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }
//
//
//
//

import type { Metadata } from "next";
import './globals.css';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Zium App Test',
  description: 'Testing routes',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="p-4">
        <nav className="flex gap-3 mb-4 border-b pb-2 text-sm">
          <Link href="/home">Home</Link>
          <Link href="/list">List</Link>
          <Link href="/liked">Liked</Link>
          <Link href="/my">My</Link>
          <Link href="/notifications">Notifications</Link>
          <Link href="/search">Search</Link>
          <Link href="/auth/login">Login</Link>
        </nav>
        {children}
      </body>
    </html>
  );
}
